### ISSUE TITLE
The plugin only played a crash game once "/alwayscratch+playername"

### ISSUE THREAD

**Issue by PaiAleMon** [goteusz-maszyk/ClientCrasher-Spigot#3]
In the fabric version of Minecraft 1.20.1, after entering "/alwayscratch+playername".
Cheet will only crash the game once. After restarting the game, 
Cheat can still access the server by joining the server again. And there was no crash game
The plugin only played a crash game once. No effect always crash

**Comment by goteusz-maszyk** [comment]
[Fabric version here](https://github.com/goteusz-maszyk/ClientCrasher-Fabric)
