### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by dol4iua** [goteusz-maszyk/ClientCrasher-Spigot#5]
I suggest adding a check for permissions and not just for 'Op', as it is simply blocked in many.

**Comment by goteusz-maszyk** [comment]
wdym?

**Comment by dol4iua** [comment]
to Grant rights to use this command by granting permission, for example, in luckperms

**Comment by okunamayanad** [comment]
Permissions like `clientcrasher.crashplayer`, `clientcrasher.crashban.add`, `clientcrasher.crashban.remove` would be really helpful for server admins as people generally don't want to just op someone (eg. a moderator has the permission to kick and crash a player, but not to crash ban or shutdown the server.)

**Comment by goteusz-maszyk** [comment]
I'll do it some day.
